In [1]:
from numpy import set_printoptions,nan,full,zeros
set_printoptions(threshold=nan)
from itertools import combinations

In [2]:
def letras(x):
    if x==0:
        letra=chr(83)
    if x==1:
        letra=chr(80)
    if x==2:
        letra=chr(68)
    if x in range (3,7):
        letra=chr(67+x)
    if x in range (7,12):
        letra=chr(68+x)
    if x in range (12,14):
        letra=chr(69+x)
    if x in range (14,21):
        letra=chr(70+x)
    return letra

In [19]:
def LSequivalentes(N,l): 
    #Para n electrones equivalentes l, genera una lista de los terminos LS permitidos
    
    #Crea una lista de todos los estados para un electrón de momento orbital l y spin 1/2
    E=full((4*l+2,2),nan)
    k=l
    for i in range(0,4*l+2,2):
        E[i,0]=k
        E[i+1]=k
        E[i,1]=1/2
        E[i+1,1]=-1/2
        k=k-1
        
    #Genera todas las combinaciones posibles para n electrones l, excluyendo las prohibidas por Pauli    
    a=list(combinations(E,N))
    
    #Crea una matriz que contiene la suma de todas las proyecciones Ml y Ms para cada combinacion de las anteriores
    b=zeros([len(a),2])
    for i in range (0,len(a)):
        if N==1:
            b[i,0]=a[i][0][0]
            b[i,1]=a[i][0][1]
        else:
            for j in range(0,len(a[0][:])):
                b[i,0]=b[i,0]+a[i][j][0]
                b[i,1]=b[i,1]+a[i][j][1]
   
    #Crea una matriz que enumera la cantidad de veces que distintos valores Ml y Ms se cruzan 
    c=zeros([2*abs(int(max(b[:,0])))+2,2*abs(int(max(b[:,1])))+2])
    for i in range(1,len(c[:,0])):
        c[i,0]=max(b[:,0])-i+1
    for i in range(1,len(c[0,:])):
        c[0,i]=max(b[:,1])-i+1
    for i in range (1,len(c[:,0])):
        for j in range(1,len(c[0,:])):
            for k in range(0,len(b[:,0])):
                if c[i,0]==b[k,0] and c[0,j]==b[k,1]:
                    c[i,j]=c[i,j]+1
                    
    #A partir de la matriz anterior, genera una lista de los terminos LS permitidos
    z=0
    i=1
    lista=list()
    listafinal=list()
    while c[i,0] >= 0:
        j=1
        while c[0,j]>=0:
            if c[i,j]>0:
                lista.append((2*c[0,j]+1,c[i,0])) 
                z=z+1
                for x in range (i,len(c[:,0])):
                    for y in range (j,len(c[0,:])):
                        c[x,y]=c[x,y]-1             
            else:
                j=j+1
        i=i+1
    listafinal.append(["2S+1","L","# de terminos"])
    listafinal.append([int(lista[0][0]),letras(int(lista[0][1])),int(1)])
    j=1
    for i in range (1,len(lista)):
        if lista[i][0]==lista[i-1][0] and lista[i][1]==lista[i-1][1]:
            listafinal[j][2]=listafinal[j][2]+int(1)
        else:
            listafinal.append([int(lista[i][0]),letras(int(lista[i][1])),int(1)])
            j=j+1
    print (z,"terminos")                
    return listafinal


In [20]:
LSequivalentes(10,3) #se muestra como ejemplo para 12 electrones f

IndexError: list index out of range

In [5]:
#a continuacion se separa el programa en bloques, para que se vea su funcionamiento intermedio

In [12]:
def electron(l):
    E=full((4*l+2,2),nan)
    k=l
    for i in range(0,4*l+2,2):
        E[i,0]=k
        E[i+1]=k
        E[i,1]=1/2
        E[i+1,1]=-1/2
        k=k-1
    return E

In [13]:
def electrones(N,l):
    E=electron(l)
    a=list(combinations(E,N))
    
    return a
a=electrones(2,1)
a

[(array([ 1.,  0.]), array([ 1., -1.])),
 (array([ 1.,  0.]), array([ 0.,  0.])),
 (array([ 1.,  0.]), array([ 0., -1.])),
 (array([ 1.,  0.]), array([-1.,  0.])),
 (array([ 1.,  0.]), array([-1., -1.])),
 (array([ 1., -1.]), array([ 0.,  0.])),
 (array([ 1., -1.]), array([ 0., -1.])),
 (array([ 1., -1.]), array([-1.,  0.])),
 (array([ 1., -1.]), array([-1., -1.])),
 (array([ 0.,  0.]), array([ 0., -1.])),
 (array([ 0.,  0.]), array([-1.,  0.])),
 (array([ 0.,  0.]), array([-1., -1.])),
 (array([ 0., -1.]), array([-1.,  0.])),
 (array([ 0., -1.]), array([-1., -1.])),
 (array([-1.,  0.]), array([-1., -1.]))]

In [14]:
b=full((len(a),2),0)
b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [15]:
N=2
def sumas(a):
    b=zeros([len(a),2])
    for i in range (0,len(a)):
        if N==1:
            b[i,0]=a[i][0][0]
            b[i,1]=a[i][0][1]
        else:
            for j in range(0,len(a[0])):
                b[i,0]=b[i,0]+a[i][j][0]
                b[i,1]=b[i,1]+a[i][j][1]
    return b
b=sumas(a)
b

array([[ 2., -1.],
       [ 1.,  0.],
       [ 1., -1.],
       [ 0.,  0.],
       [ 0., -1.],
       [ 1., -1.],
       [ 1., -2.],
       [ 0., -1.],
       [ 0., -2.],
       [ 0., -1.],
       [-1.,  0.],
       [-1., -1.],
       [-1., -1.],
       [-1., -2.],
       [-2., -1.]])

In [16]:
def tabla(b):
    
    c=zeros([2*int(max(b[:,0]))+2,2*int(max(b[:,1]))+2])
    
    for i in range(1,len(c[:,0])):
        c[i,0]=max(b[:,0])-i+1
    for i in range(1,len(c[0,:])):
        c[0,i]=max(b[:,1])-i+1
    for i in range (1,len(c[:,0])):
        for j in range(1,len(c[0,:])):
            for k in range(0,len(b[:,0])):
                if c[i,0]==b[k,0] and c[0,j]==b[k,1]:
                    c[i,j]=c[i,j]+1
    return c
c=tabla(b)
c

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 1.,  1.],
       [ 0.,  1.],
       [-1.,  1.],
       [-2.,  0.]])

In [17]:
def criterio(c):
    z=0
    i=1
    lista=list()
    listafinal=list()
    while c[i,0] >= 0:
        j=1
        while c[0,j]>=0:
            if c[i,j]>0:
                lista.append((2*c[0,j]+1,c[i,0])) 
                z=z+1
                for x in range (i,len(c[:,0])):
                    for y in range (j,len(c[0,:])):
                        c[x,y]=c[x,y]-1             
            else:
                j=j+1
        i=i+1
        
    listafinal.append(["2S+1","L","# de términos"])
    listafinal.append([int(lista[0][0]),letras(int(lista[0][1])),int(1)])
    j=1
    for i in range (1,len(lista)):
        if lista[i][0]==lista[i-1][0] and lista[i][1]==lista[i-1][1]:
            listafinal[j][2]=listafinal[j][2]+int(1)
        else:
            listafinal.append([int(lista[i][0]),letras(int(lista[i][1])),int(1)])
            j=j+1
    print (z,"términos")                
    return listafinal

criterio(c)

IndexError: index 2 is out of bounds for axis 1 with size 2

In [18]:
lsequivalentes

NameError: name 'lsequivalentes' is not defined